### ISSUE TITLE
add typescript support

### ISSUE THREAD

**Issue by cafeed28** [Nerwind/node-random#1]
`npx typescript index.js --declaration --allowJs --emitDeclarationOnly --outDir ./` когда обновляешь index.js
и добавь в `package.json` `"types": "index.d.ts"`

**Comment by Nerwind** [comment]
как же ты заебал блять я в это время сплю

**Comment by Nerwind** [comment]
всё добавил заебись теперь пошёл нахуй

**Comment by cafeed28** [comment]
:overdrive_ebalo:
